name: Android Release

on:
  push:
    tags:
      - 'v*' # Only trigger on version tags like v1.2.5

jobs:
  build-release:
    name: Build & Release Signed APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Decode keystore
      run: echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 -d > app/keystore.jks

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build signed release APK
      run: ./gradlew assembleRelease
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

    - name: Upload release APK to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: app/release/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 
